### ISSUE TITLE
Update website regarding DApp launch

### ISSUE THREAD

**Issue by EmmanuelDrouin** [Quiver-Protocol/quiver-website#19]
Regarding the coming launch of the DApp to the public, the website needs to be updated to deliver the proper messages and call to action.
The changes need to be live at the same moment the DApp is live for the public.

@gopherquiv I let you assign the right person to this task ;)

todo:

- [ ] Update header "badge"
  - Change content for something like "Emotional NFTS Sale - Become an investor now"
  - Update the "badge" to redirect "on click" to the DApp
  - <img width="721" alt="Screen Shot 2021-06-01 at 17 25 44" src="https://user-images.githubusercontent.com/15095289/120308539-66f8df80-c2fe-11eb-965a-6b281e0af6fc.png">

- [ ] NFT section
  - Replace the "mailing cta" and content above it (coming early...) with a primary CTA linked to the DApp
  - <img width="615" alt="Screen Shot 2021-06-01 at 17 30 02" src="https://user-images.githubusercontent.com/15095289/120309083-01592300-c2ff-11eb-8faf-3bedde7f9dee.png">

**Comment by gopherquiv** [comment]
Ok
